permalink: /:year/:month/:title.html
safe: true
markdown: kramdown
highlighter: rouge
syntax-highlighting:
  enabled: true
  css: css/syntax.css
paginate: 2
excerpt_separator: <!--more-->
twitter: jkirchartz
gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
