permalink: /:year/:month/:name.html
markdown: rdiscount

title : JKirchartz -  Web Developer n'at
author :
  name : Joel Kirchartz
  email : JKirchartz@gmail.com
  github : JKirchartz
  twitter : JKirchartz
