permalink: /:year/:month/:title.html
safe: true
markdown: rdiscount
highlighter: pygments
syntax-highlighting:
  enabled: true
  css: css/syntax.css
paginate: 2
twitter: jkirchartz
gems: [jekyll-paginate]
