permalink: /:year/:month/:title.html
safe: true
markdown: kramdown
highlighter: rouge
syntax-highlighting:
  enabled: true
  css: css/syntax.css
paginate: 2
excerpt_separator: <!--more-->
title: JKirchartz - Web Yinzer n'at
description: Musings, Music, and More from the WebYinzer n'at.
author: jkirchartz
gems:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
