permalink: /:year/:month/:title.html
safe: true
markdown: kramdown
highlighter: rouge
syntax-highlighting:
  enabled: true
paginate: 2
sass:
  style: compressed
excerpt_separator: <!--more-->
title: JKirchartz - Web Yinzer n'at
description: Musings, Music, and More from the WebYinzer n'at.
author: jkirchartz
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji
  - jekyll-gist
  - github-metadata
